Repository su-per-no-va/fashion-nova, pull requests merged in 2024-08, with the labels that each got.

#159 138 백이랑 프론트 연결 - 회원가입,로그인
  src/main/java/com/supernova/fashionnova/front/HomeController.java
  src/main/java/com/supernova/fashionnova/global/config/WebConfig.java
  src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java
  src/main/java/com/supernova/fashionnova/security/JwtAuthenticationFilter.java
  src/main/java/com/supernova/fashionnova/user/User.java
  src/main/java/com/supernova/fashionnova/user/UserController.java
  src/main/java/com/supernova/fashionnova/user/dto/SignupRequestDto.java
  src/main/resources/application.properties
  src/main/resources/static/js/login.js
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
  src/test/java/com/supernova/fashionnova/user/UserControllerTest.java
Labels: enhancement

#160 [🎉FEATURE] 147 카카오 소셜 로그인
  src/main/java/com/supernova/fashionnova/global/config/RestTemplateConfig.java
  src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java
  src/main/java/com/supernova/fashionnova/product/ProductController.java
  src/main/java/com/supernova/fashionnova/product/ProductRepositoryQueryImpl.java
  src/main/java/com/supernova/fashionnova/security/JwtAuthorizationFilter.java
  src/main/java/com/supernova/fashionnova/security/JwtUtil.java
  src/main/java/com/supernova/fashionnova/user/KakaoService.java
  src/main/java/com/supernova/fashionnova/user/KakaoUserInfoDto.java
  src/main/java/com/supernova/fashionnova/user/User.java
  src/main/java/com/supernova/fashionnova/user/UserController.java
  src/main/java/com/supernova/fashionnova/user/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/js/basic.js
  src/main/resources/templates/login.html
Labels: enhancement

#162 [♻️ REFACTOR] 147 카카오 소셜 로그인
  src/main/java/com/supernova/fashionnova/user/UserController.java
  src/main/resources/js/basic.js
Labels: enhancement

#167 ♻️ REFACTOR: 카카오 소셜 로그인(add refreshToken)
  src/main/java/com/supernova/fashionnova/security/JwtUtil.java
  src/main/java/com/supernova/fashionnova/user/KakaoService.java
  src/main/java/com/supernova/fashionnova/user/User.java
  src/main/java/com/supernova/fashionnova/user/UserController.java
Labels: enhancement

#169 [🎉FEATURE] 배송지 삭제
  src/main/java/com/supernova/fashionnova/address/AddressController.java
  src/main/java/com/supernova/fashionnova/address/AddressService.java
  src/main/java/com/supernova/fashionnova/address/dto/AddressDeleteRequestDto.java
  src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java
  src/test/java/api/address.http
Labels: enhancement

#171 [♻️ REFACTOR] 엔티티 리팩토링
  src/main/java/com/supernova/fashionnova/admin/AdminController.java
  src/main/java/com/supernova/fashionnova/cart/Cart.java
  src/main/java/com/supernova/fashionnova/global/common/MileageScheduler.java
  src/main/java/com/supernova/fashionnova/global/config/JpaAuditingConfig.java
  src/main/java/com/supernova/fashionnova/global/faker/DataGenerator.java
  src/main/java/com/supernova/fashionnova/global/faker/DataInitializer.java
  src/main/java/com/supernova/fashionnova/product/Product.java
  src/main/java/com/supernova/fashionnova/review/Review.java
  src/main/java/com/supernova/fashionnova/user/User.java
  src/main/java/com/supernova/fashionnova/warn/Warn.java
  src/test/java/com/supernova/fashionnova/product/ProductRepositoryQueryImplTest.java
Labels: enhancement

#173 [🎉FEATURE] 프론트-백 연결-카트-유저
  src/main/java/com/supernova/fashionnova/admin/AdminController.java
  src/main/java/com/supernova/fashionnova/admin/AdminService.java
  src/main/java/com/supernova/fashionnova/cart/CartService.java
  src/main/java/com/supernova/fashionnova/cart/dto/CartItemDto.java
  src/main/java/com/supernova/fashionnova/product/Product.java
  src/main/java/com/supernova/fashionnova/product/dto/ProductResponseDto.java
  src/main/java/com/supernova/fashionnova/upload/FileUploadUtil.java
  src/main/resources/static/css/main.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/about.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/index.html
  src/main/resources/templates/my-page.html
  src/main/resources/templates/product.html
  src/main/resources/templates/question.html
  src/main/resources/templates/shoping-cart.html
  src/main/resources/templates/wish-list.html
Labels: enhancement

#184 [🐞BUG] 위시리스트 조회
  src/main/java/com/supernova/fashionnova/domain/wish/WishController.java
  src/main/java/com/supernova/fashionnova/domain/wish/WishService.java
  src/main/java/com/supernova/fashionnova/domain/wish/dto/WishResponseDto.java
Labels: enhancement

#185 [🎉FEATURE] 프론트 연결 장바구니-유저 정보
  src/main/java/com/supernova/fashionnova/domain/address/dto/AddressResponseDto.java
  src/main/resources/templates/my-info.html
  src/main/resources/templates/wish-list.html
Labels: enhancement

#189 [♻️ REFACTOR] 리스폰스 id 달아주기
  src/main/java/com/supernova/fashionnova/domain/cart/CartService.java
  src/main/java/com/supernova/fashionnova/domain/cart/dto/CartItemDto.java
  src/main/java/com/supernova/fashionnova/domain/cart/dto/CartResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/user/dto/UserResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/warn/dto/WarnResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/wish/dto/WishResponseDto.java
  src/test/java/com/supernova/fashionnova/wish/WishControllerTest.java
  src/test/java/com/supernova/fashionnova/wish/WishServiceTest.java
Labels: enhancement

#191 [🎉FEATURE] 178 feature 상품조회 프론트
  src/main/java/com/supernova/fashionnova/domain/product/ProductController.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductRepositoryQuery.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductRepositoryQueryImpl.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductService.java
  src/main/java/com/supernova/fashionnova/domain/product/dto/ProductResponseDto.java
  src/main/resources/static/js/main.js
  src/main/resources/templates/product.html
  src/main/resources/templates/wish-list.html
Labels: enhancement

#192 🐞 FIX: 조건별 상품 조회 프론트 (버그 수정)
  src/main/resources/static/images/1000004221_detail_032.jpg
  src/main/resources/static/images/110733453.1.jpg
  src/main/resources/static/images/1702445801715-e3c516a4-0c03-42a5-ac5a-f92f26cb8f99.jpg
  src/main/resources/static/images/198b7b543f3b84374fca820d91263778.jpg
  src/main/resources/static/images/1d748fd4-b904-41e1-803c-71314667369a.jpg
  src/main/resources/static/images/240130008555911.jpg
  src/main/resources/static/images/4208879_17199916914172_500.jpg
  src/main/resources/static/images/601e3a0e616bc11cc9939d4d30e835ab.jpg
  src/main/resources/static/images/B004810025.jpg
  src/main/resources/static/images/K1690275313299050BE01_LM1.jpg
  src/main/resources/static/images/PS19111700365.jpg
  src/main/resources/static/images/VN0007NKBYS1_VN0007NKBYS1_primary.jpg
  src/main/resources/static/images/a585e107df1755b591d5512c10a53393956ee580de435ba73cec380a0def.jpg
  src/main/resources/static/images/dbdd9d0a-4018-4685-b8f6-66e4f3a1be28.jpg
  src/main/resources/static/images/ec8732d4bc252fd26a34be2de867def1.jpg
  src/main/resources/static/images/jCOR6CmoSJ-f8vnkQFLazw.jpg
  src/main/resources/static/images/optimize.jpg
  src/main/resources/templates/product.html
Labels: enhancement

#196 🐞 FIX: 조건별 상품 조회 프론트 (버그 수정)
  src/main/java/com/supernova/fashionnova/domain/product/ProductController.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductService.java
Labels: enhancement

#200 [♻️ REFACTOR] 서비스 컨트롤러 리팩토링
  src/main/java/com/supernova/fashionnova/admin/AdminController.java
  src/main/java/com/supernova/fashionnova/admin/AdminService.java
  src/main/java/com/supernova/fashionnova/domain/address/AddressController.java
  src/main/java/com/supernova/fashionnova/domain/address/AddressService.java
  src/main/java/com/supernova/fashionnova/domain/cart/CartController.java
  src/main/java/com/supernova/fashionnova/domain/cart/CartService.java
  src/main/java/com/supernova/fashionnova/domain/coupon/CouponController.java
  src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java
  src/main/java/com/supernova/fashionnova/domain/mileage/MileageController.java
  src/main/java/com/supernova/fashionnova/domain/mileage/MileageService.java
  src/main/java/com/supernova/fashionnova/domain/order/Order.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderController.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderDetail.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderDetailController.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderDetailRepository.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderDetailService.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderService.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderStatus.java
  src/main/java/com/supernova/fashionnova/domain/order/OrdersRepository.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductController.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionController.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionService.java
  src/main/java/com/supernova/fashionnova/domain/review/ReviewController.java
  src/main/java/com/supernova/fashionnova/domain/review/ReviewService.java
  src/main/java/com/supernova/fashionnova/domain/user/KakaoService.java
  src/main/java/com/supernova/fashionnova/domain/user/KakaoUserInfoDto.java
  src/main/java/com/supernova/fashionnova/domain/user/User.java
  src/main/java/com/supernova/fashionnova/domain/user/UserController.java
  src/main/java/com/supernova/fashionnova/domain/user/UserGrade.java
  src/main/java/com/supernova/fashionnova/domain/user/UserRole.java
  src/main/java/com/supernova/fashionnova/domain/user/UserService.java
  src/main/java/com/supernova/fashionnova/domain/user/UserStatus.java
  src/main/java/com/supernova/fashionnova/domain/warn/WarnController.java
  src/main/java/com/supernova/fashionnova/domain/warn/warnService.java
  src/main/java/com/supernova/fashionnova/domain/wish/WishController.java
  src/main/java/com/supernova/fashionnova/domain/wish/WishService.java
  src/test/java/com/supernova/fashionnova/cart/CartControllerTest.java
  src/test/java/com/supernova/fashionnova/cart/CartServiceTest.java
Labels: enhancement

#201 116 feature 프론트 구현
  src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java
  src/main/resources/static/js/login.js
  src/main/resources/templates/login.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/shoping-cart.html
  src/main/resources/templates/signup.html
Labels: enhancement

#204 [🐞BUG] 문의 기능 수정
  .github/workflows/cd.yml
  src/main/java/com/supernova/fashionnova/admin/AdminService.java
  src/main/java/com/supernova/fashionnova/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/order/dto/OrderDetailResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/question/Question.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionController.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionRepository.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionService.java
  src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionDetailResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionRequestDto.java
  src/main/java/com/supernova/fashionnova/domain/review/ReviewController.java
  src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java
  src/main/java/com/supernova/fashionnova/global/faker/DataGenerator.java
  src/test/java/api/admin.http
  src/test/java/api/question.http
  src/test/java/api/user.http
  src/test/java/com/supernova/fashionnova/admin/AdminServiceTest.java
  src/test/java/com/supernova/fashionnova/question/QuestionControllerTest.java
  src/test/java/com/supernova/fashionnova/question/QuestionServiceTest.java
Labels: enhancement

#216 [♻️ REFACTOR] 리뷰 오더 페이지 모달 수정
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/order.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/review.html
Labels: enhancement

#217 186 프론트 연결- 리뷰-문의 및 다른 페이지
  src/main/java/com/supernova/fashionnova/domain/mileage/MileageRepository.java
  src/main/java/com/supernova/fashionnova/domain/mileage/MileageService.java
  src/main/java/com/supernova/fashionnova/domain/mileage/dto/MileageResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionController.java
  src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionResponseDto.java
  src/main/resources/static/js/common.js
  src/main/resources/templates/grade.html
  src/main/resources/templates/index.html
  src/main/resources/templates/my-mileage.html
  src/main/resources/templates/my-question-detail.html
  src/main/resources/templates/my-question.html
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/order.html
  src/main/resources/templates/question.html
  src/test/java/com/supernova/fashionnova/mileage/MileageControllerTest.java
  src/test/java/com/supernova/fashionnova/mileage/MileageServiceTest.java
Labels: enhancement

#218 [🎉FEATURE] 이메일 인증
  .github/workflows/cd.yml
  build.gradle
  src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java
  src/main/java/com/supernova/fashionnova/global/mail/MailController.java
  src/main/java/com/supernova/fashionnova/global/mail/MailService.java
  src/main/resources/application.properties
Labels: enhancement

#224 [🎉FEATURE] 프론트-오더디테일-전체 헤더
  src/main/java/com/supernova/fashionnova/admin/AdminController.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderDetailController.java
  src/main/java/com/supernova/fashionnova/domain/order/dto/AllOrderResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/order/dto/OrderDetailResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionService.java
  src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java
  src/main/java/com/supernova/fashionnova/global/security/JwtAuthenticationFilter.java
  src/main/java/com/supernova/fashionnova/global/security/JwtAuthorizationFilter.java
  src/main/resources/static/js/common.js
  src/main/resources/templates/about.html
  src/main/resources/templates/admin/index.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/grade.html
  src/main/resources/templates/index.html
  src/main/resources/templates/my-coupon.html
  src/main/resources/templates/my-info.html
  src/main/resources/templates/my-mileage.html
  src/main/resources/templates/my-page.html
  src/main/resources/templates/my-question-detail.html
  src/main/resources/templates/my-question.html
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/order.html
  src/main/resources/templates/product.html
  src/main/resources/templates/question.html
  src/main/resources/templates/review.html
  src/main/resources/templates/shoping-cart.html
  src/main/resources/templates/wish-list.html
Labels: enhancement

#228 🐞 FIX(문의): 관계 수정
  .github/workflows/cd.yml
  src/main/java/com/supernova/fashionnova/domain/question/Question.java
  src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionDetailResponseDto.java
  src/test/java/com/supernova/fashionnova/admin/AdminControllerTest.java
Labels: enhancement

#230 225 feature front admin payment
  .gitignore
  src/main/java/com/supernova/fashionnova/admin/AdminController.java
  src/main/java/com/supernova/fashionnova/admin/AdminService.java
  src/main/java/com/supernova/fashionnova/admin/dto/AllReviewResponseDto.java
  src/main/java/com/supernova/fashionnova/admin/dto/UserProfileResponseDto.java
  src/main/java/com/supernova/fashionnova/admin/dto/UsersCouponAndMileageResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/address/AddressRepository.java
  src/main/java/com/supernova/fashionnova/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductImage.java
  src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/user/User.java
  src/main/java/com/supernova/fashionnova/domain/user/UserController.java
  src/main/java/com/supernova/fashionnova/domain/user/UserService.java
  src/main/java/com/supernova/fashionnova/domain/user/dto/UserResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/user/dto/UserRoleResponseDto.java
  src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java
  src/main/java/com/supernova/fashionnova/global/upload/FileUploadUtil.java
  src/main/resources/static/admin/css/admin-modal.css
  src/main/resources/static/admin/js/admin-check.js
  src/main/resources/static/admin/js/admin-product-create.js
  src/main/resources/static/admin/js/admin-warning-modal.js
  src/main/resources/static/js/login.js
  src/main/resources/templates/admin/admin-coupon-mileage.html
  src/main/resources/templates/admin/admin-login.html
  src/main/resources/templates/admin/admin-product-create.html
  src/main/resources/templates/admin/admin-product-update.html
  src/main/resources/templates/admin/admin-product.html
  src/main/resources/templates/admin/admin-question.html
  src/main/resources/templates/admin/admin-review.html
  src/main/resources/templates/admin/admin-tables.html
  src/main/resources/templates/admin/admin-user.html
  src/main/resources/templates/admin/index.html
Labels: enhancement

#232 [🐞BUG] 테스트 코드, 어드민 리팩토링
  src/main/java/com/supernova/fashionnova/admin/AdminController.java
  src/main/java/com/supernova/fashionnova/admin/AdminService.java
  src/main/java/com/supernova/fashionnova/admin/dto/AllReviewResponseDto.java
  src/main/java/com/supernova/fashionnova/admin/dto/UserProfileResponseDto.java
  src/main/java/com/supernova/fashionnova/admin/dto/UsersCouponAndMileageResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/cart/CartController.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionController.java
  src/main/java/com/supernova/fashionnova/domain/question/QuestionService.java
  src/main/java/com/supernova/fashionnova/domain/user/UserController.java
  src/main/java/com/supernova/fashionnova/domain/user/UserService.java
  src/test/java/com/supernova/fashionnova/admin/AdminServiceTest.java
  src/test/java/com/supernova/fashionnova/question/QuestionControllerTest.java
  src/test/java/com/supernova/fashionnova/question/QuestionServiceTest.java
Labels: enhancement

#233 [🎉FEATURE] 상품상세 조회 프론트
  src/main/java/com/supernova/fashionnova/domain/cart/dto/CartRequestDto.java
  src/main/java/com/supernova/fashionnova/domain/product/Product.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductController.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductService.java
  src/main/java/com/supernova/fashionnova/domain/product/dto/ProductResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/review/ReviewController.java
  src/main/java/com/supernova/fashionnova/domain/review/ReviewService.java
  src/main/java/com/supernova/fashionnova/domain/review/dto/ReviewImageResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/supernova/fashionnova/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/supernova/fashionnova/global/faker/DataGenerator.java
  src/main/java/com/supernova/fashionnova/global/security/JwtAuthorizationFilter.java
  src/main/resources/templates/index.html
  src/main/resources/templates/product-detail.html
Labels: enhancement

#235 [🎉FEATURE] 프론트 페이징 처리
  src/main/java/com/supernova/fashionnova/domain/question/QuestionController.java
  src/main/resources/templates/my-mileage.html
  src/main/resources/templates/my-page.html
  src/main/resources/templates/my-question.html
  src/main/resources/templates/payment.html
  src/main/resources/templates/payments-completed.html
  src/main/resources/templates/review.html
Labels: enhancement

#236 [🎉FEATURE] 상품조회 프론트
  src/main/java/com/supernova/fashionnova/domain/review/ReviewService.java
  src/main/resources/static/images/14acd9cfbfa4de9eb9e8c27e72094769.jpg
  src/main/resources/static/images/m_1520917346_7550_20180313_135826.jpg
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/product.html
  src/main/resources/templates/shoping-cart.html
Labels: enhancement

#237 [🎉FEATURE] 상품조회 프론트
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/product.html
Labels: enhancement

#239 [🐞BUG] 유저 경고 로직 수정
  src/main/java/com/supernova/fashionnova/admin/AdminService.java
  src/main/java/com/supernova/fashionnova/domain/warn/WarnRepository.java
  src/test/java/api/admin.http
Labels: enhancement

#240 [🐞BUG] 쿠폰 기간
  src/main/java/com/supernova/fashionnova/domain/coupon/Coupon.java
  src/main/java/com/supernova/fashionnova/domain/coupon/CouponRepository.java
  src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java
  src/main/java/com/supernova/fashionnova/domain/coupon/dto/CouponRequestDto.java
  src/main/java/com/supernova/fashionnova/domain/user/UserService.java
  src/test/java/api/admin.http
  src/test/java/api/user.http
  src/test/java/com/supernova/fashionnova/admin/AdminControllerTest.java
  src/test/java/com/supernova/fashionnova/product/ProductServiceTest.java
  src/test/java/com/supernova/fashionnova/review/ReviewControllerTest.java
  src/test/java/com/supernova/fashionnova/review/ReviewServiceTest.java
  src/test/java/com/supernova/fashionnova/user/UserServiceTest.java
  src/test/java/com/supernova/fashionnova/wish/WishControllerTest.java
  src/test/java/com/supernova/fashionnova/wish/WishServiceTest.java
Labels: enhancement

#245 [🐞BUG] 빌드 오류 해결
  src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java
  src/test/java/com/supernova/fashionnova/order/OrderControllerTest.java
  src/test/java/com/supernova/fashionnova/order/OrderDetailControllerTest.java
  src/test/java/com/supernova/fashionnova/order/OrderServiceTest.java
Labels: enhancement

#247 [🎉FEATURE] 상품조회 프론트
  src/main/java/com/supernova/fashionnova/domain/product/ProductRepositoryQueryImpl.java
  src/main/resources/static/js/main.js
  src/main/resources/templates/grade.html
  src/main/resources/templates/product.html
Labels: enhancement

#251 [🎉FEATURE] 상품조회 프론트
  src/main/resources/templates/product-detail.html
Labels: enhancement

#252 [♻️ REFACTOR] / [🐞BUG] 사용자 페이지 버그 수정
  src/main/resources/static/css/login.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/about.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/index.html
  src/main/resources/templates/product.html
  src/main/resources/templates/signup.html
Labels: bug, enhancement

#250 [♻️ REFACTOR] / [🐞BUG] 페이지 리펙토링 및 버그 픽스
  src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java
  src/main/resources/templates/kakaopay.html
  src/main/resources/templates/my-info.html
  src/main/resources/templates/order.html
  src/main/resources/templates/payment.html
  src/main/resources/templates/payments-completed.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/wish-list.html
Labels: enhancement

#255 [♻️ REFACTOR] 위시 최신순 정렬 조회
  src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java
  src/main/java/com/supernova/fashionnova/domain/wish/Wish.java
  src/main/java/com/supernova/fashionnova/domain/wish/WishRepository.java
  src/main/java/com/supernova/fashionnova/domain/wish/WishService.java
  src/test/java/api/wish.http
Labels: enhancement

#258 패션노바 0.95
  src/main/resources/templates/about.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/grade.html
  src/main/resources/templates/index.html
  src/main/resources/templates/my-coupon.html
  src/main/resources/templates/my-info.html
  src/main/resources/templates/my-mileage.html
  src/main/resources/templates/my-page.html
  src/main/resources/templates/my-question-detail.html
  src/main/resources/templates/my-question.html
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/order.html
  src/main/resources/templates/payment-one.html
  src/main/resources/templates/payment.html
  src/main/resources/templates/payments-completed.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/product.html
  src/main/resources/templates/question.html
  src/main/resources/templates/review.html
  src/main/resources/templates/shoping-cart.html
  src/main/resources/templates/wish-list.html
Labels: enhancement

#259 [🐞BUG] 카카오페이 주소 배포된주소로 수정
  src/main/java/com/supernova/fashionnova/domain/review/ReviewController.java
  src/main/java/com/supernova/fashionnova/domain/user/KakaoService.java
  src/main/java/com/supernova/fashionnova/domain/user/UserController.java
  src/main/java/com/supernova/fashionnova/global/security/JwtAuthorizationFilter.java
  src/main/java/com/supernova/fashionnova/payment/KakaoPayController.java
  src/main/java/com/supernova/fashionnova/payment/KakaoPayService.java
  src/main/resources/templates/payment.html
Labels: bug

#265 [♻️ REFACTOR] 유저테스트 중 수정
  src/main/generated/com/supernova/fashionnova/domain/address/QAddress.java
  src/main/generated/com/supernova/fashionnova/domain/answer/QAnswer.java
  src/main/generated/com/supernova/fashionnova/domain/cart/QCart.java
  src/main/generated/com/supernova/fashionnova/domain/coupon/QCoupon.java
  src/main/generated/com/supernova/fashionnova/domain/mileage/QMileage.java
  src/main/generated/com/supernova/fashionnova/domain/order/QOrder.java
  src/main/generated/com/supernova/fashionnova/domain/order/QOrderDetail.java
  src/main/generated/com/supernova/fashionnova/domain/product/QProduct.java
  src/main/generated/com/supernova/fashionnova/domain/product/QProductDetail.java
  src/main/generated/com/supernova/fashionnova/domain/product/QProductImage.java
  src/main/generated/com/supernova/fashionnova/domain/question/QQuestion.java
  src/main/generated/com/supernova/fashionnova/domain/question/QQuestionImage.java
  src/main/generated/com/supernova/fashionnova/domain/review/QReview.java
  src/main/generated/com/supernova/fashionnova/domain/review/QReviewImage.java
  src/main/generated/com/supernova/fashionnova/domain/user/QUser.java
  src/main/generated/com/supernova/fashionnova/domain/warn/QWarn.java
  src/main/generated/com/supernova/fashionnova/domain/wish/QWish.java
  src/main/generated/com/supernova/fashionnova/global/common/QTimestamped.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderController.java
  src/main/java/com/supernova/fashionnova/domain/order/OrderService.java
  src/main/resources/templates/about.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/grade.html
  src/main/resources/templates/index.html
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/product.html
  src/main/resources/templates/question.html
  src/main/resources/templates/wish-list.html
Labels: enhancement

#266 [🐞BUG] 상품조회, 상품디테일 에러수정
  src/main/java/com/supernova/fashionnova/domain/order/OrderDetailController.java
  src/main/java/com/supernova/fashionnova/domain/order/OrdersRepository.java
  src/main/java/com/supernova/fashionnova/domain/order/dto/AllOrderResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/order/dto/OrderDetailResponseDto.java
  src/main/java/com/supernova/fashionnova/domain/product/ProductService.java
  src/main/resources/static/js/main.js
  src/main/resources/templates/my-info.html
  src/main/resources/templates/order-detail.html
  src/main/resources/templates/product.html
Labels: enhancement

#267 [🎉FEATURE] 유저 경고 조회 기능 구현
  src/main/java/com/supernova/fashionnova/domain/warn/WarnController.java
  src/main/java/com/supernova/fashionnova/domain/warn/WarnService.java
  src/main/java/com/supernova/fashionnova/front/HomeController.java
  src/main/resources/application.properties
  src/main/resources/templates/my-page.html
  src/main/resources/templates/order.html
  src/main/resources/templates/warn.html
  src/test/java/api/warn.http
Labels: enhancement

#268 [♻️ REFACTOR] 경고메시지, 얼럿창 버그, 페이지 최신순 정렬
  src/main/resources/templates/my-coupon.html
  src/main/resources/templates/my-mileage.html
  src/main/resources/templates/my-question.html
  src/main/resources/templates/order.html
  src/main/resources/templates/payment-one.html
  src/main/resources/templates/payment.html
  src/main/resources/templates/product-detail.html
  src/main/resources/templates/product.html
  src/main/resources/templates/review.html
  src/main/resources/templates/warn.html
Labels: enhancement

#269 🐞 FIX: 검색 후 찜 추가 삭제 에러 수정
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/product.html
Labels: enhancement

#271 ♻️ REFACTOR(환경변수): 주소 로컬/배포된주소 환경변수로 추가
  .github/workflows/cd.yml
  src/main/java/com/supernova/fashionnova/payment/KakaoPayService.java
  src/main/resources/application.properties
  src/main/resources/templates/order-detail.html
Labels: enhancement

#279 [🎉FEATURE] 리드미 작성
  README.md
Labels: enhancement
